name: outdoor-rec
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=23.1.0=pyh71513ae_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_win64_mkl
  - blosc=1.21.4=hdccc3a2_0
  - boost-cpp=1.78.0=h9f4b32c_3
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py311ha68e1ae_1005
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.5.7=h56e8100_0
  - cairo=1.16.0=hdecc03f_1016
  - ceres-solver=2.1.0=hb02fd38_1
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py311h7d9ee11_3
  - cfitsio=4.2.0=h9ebe7e4_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.7=py311h005e61a_0
  - coverage=7.2.5=py311ha68e1ae_0
  - cryptography=40.0.2=py311h28e9c30_0
  - curl=8.1.0=h68f0423_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - draco=1.5.6=h181d51b_0
  - eigen=3.4.0=h2d74725_0
  - exiv2=0.27.6=hadc2d18_1
  - expat=2.5.0=h63175ca_1
  - fiona=1.9.1=py311heda8569_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.4=py311ha68e1ae_0
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - future=0.18.3=pyhd8ed1ab_0
  - gdal=3.6.4=py311heaf1029_2
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.13.0=pyhd8ed1ab_0
  - geopandas-base=0.13.0=pyha770c72_0
  - geopy=2.3.0=pyhd8ed1ab_0
  - geos=3.11.2=h1537add_0
  - geotiff=1.7.1=h7222e44_8
  - gettext=0.21.1=h5728263_0
  - gflags=2.2.2=ha925a31_1004
  - glib=2.76.2=h12be248_0
  - glib-tools=2.76.2=h12be248_0
  - glog=0.6.0=h4797de2_0
  - gsl=2.7=hdfb1a43_0
  - gst-plugins-base=1.22.3=h001b923_1
  - gstreamer=1.22.3=h6b5321d_1
  - hdf4=4.2.15=h1334946_6
  - hdf5=1.14.0=nompi_h918d9b7_103
  - httplib2=0.22.0=pyhd8ed1ab_0
  - icu=72.1=h63175ca_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - kealib=1.5.1=hc8369a0_3
  - kiwisolver=1.4.4=py311h005e61a_1
  - krb5=1.20.1=heb0366b_0
  - laz-perf=3.3.0=h91493d7_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libaec=1.0.6=h63175ca_1
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang=16.0.3=default_h8b4101f_1
  - libclang13=16.0.3=default_h45d3cf4_1
  - libcurl=8.1.0=h68f0423_0
  - libdeflate=1.18=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.6.4=h36c8192_2
  - libglib=2.76.2=he8f3873_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=16_win64_mkl
  - liblapacke=3.9.0=16_win64_mkl
  - libnetcdf=4.9.2=nompi_hc664c2b_104
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libpq=15.3=ha9684e8_0
  - libprotobuf=3.21.12=h12be248_0
  - librttopo=1.1.0=he1da8c1_13
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=h50a8ebb_25
  - libsqlite=3.42.0=hcfcfb64_0
  - libssh2=1.10.0=h9a1e1f7_3
  - libtiff=4.5.0=h6c8260b_6
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.3.0=hcfcfb64_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.10.4=hc3477c8_0
  - libxslt=1.1.37=h0192164_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_4
  - lxml=4.9.2=py311h5942461_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py311ha68e1ae_0
  - matplotlib=3.7.1=py311h1ea47a8_0
  - matplotlib-base=3.7.1=py311h6e989c2_0
  - mkl=2022.1.0=h6a75c08_874
  - mkl-devel=2022.1.0=h57928b3_875
  - mkl-include=2022.1.0=h6a75c08_874
  - mock=5.0.2=pyhd8ed1ab_0
  - movingpandas=0.16.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - munch=3.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=3.1=pyhd8ed1ab_0
  - nitro=2.7.dev8=h1537add_0
  - nose2=0.9.2=py_0
  - numpy=1.24.3=py311h0b4df5a_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.0=hcfcfb64_3
  - owslib=0.29.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.1=py311hf63dbb6_1
  - pcre2=10.40=h17e33f8_0
  - pdal=2.5.3=hac3c4d1_0
  - pillow=9.5.0=py311hde623f7_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - plotly=5.14.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.05.0=h45d20d0_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=hd87cd2b_0
  - proj=9.2.0=heca977f_0
  - psycopg2=2.9.3=py311hb12f294_2
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py311h095e9de_1
  - pyqt=5.15.7=py311h125bc19_3
  - pyqt5-sip=12.11.0=py311h12c1d0e_3
  - pyqtwebkit=5.15.9=py311h5a77453_1
  - pysocks=1.7.1=pyh0701188_6
  - python=3.11.3=h2628c8c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py311ha68e1ae_5
  - qca=2.3.6=h2624d1c_0
  - qgis=3.30.2=py311h1e9536a_1
  - qjson=0.9.0=h04a78d6_1009
  - qscintilla2=2.14.0=py311h5a77453_0
  - qt-main=5.15.8=h2c8576c_11
  - qtkeychain=0.14.0=h04a78d6_0
  - qtwebkit=5.212=hab0d466_10
  - qwt=6.2.0=h07be427_5
  - requests=2.29.0=pyhd8ed1ab_0
  - rtree=1.0.1=py311hcacb13a_1
  - scikit-learn=1.2.2=py311h142b183_1
  - scipy=1.10.1=py311h37ff6ca_3
  - setuptools=67.7.2=pyhd8ed1ab_0
  - shapely=2.0.1=py311h343093d_1
  - sip=6.7.9=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - sqlite=3.42.0=hcfcfb64_0
  - suitesparse=5.4.0=h5d0cbe0_1
  - tbb=2021.9.0=h91493d7_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=h3132609_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py311ha68e1ae_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vc=14.3=hb25d44b_16
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wheel=0.40.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xerces-c=3.2.4=h63175ca_2
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.5.0=pyhd8ed1ab_1
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h12be248_6
prefix: C:\Users\mketchin\AppData\Local\miniconda3\envs\outdoor-rec
